version: '3.9'

services:
  java_app:
    container_name: java_app
    image: pee-retotcs-app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:h2:mem:retodb
      - DATABASE_USERNAME=sa
      - DATABASE_PASSWORD=password
